# Generated by Django 5.2 on 2025-05-02 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProgress",
        ),
    ]
