# Generated by Django 5.2 on 2025-05-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_task_options_alter_task_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="slug",
            field=models.SlugField(default="hah", max_length=200, unique=True),
        ),
    ]
