# Generated by Django 5.2 on 2025-05-05 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_studymaterial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studymaterial",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.subject",
            ),
        ),
    ]
