# Generated by Django 5.2 on 2025-05-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="content",
            field=models.TextField(
                blank=True, help_text="Поддерживает LaTeX формулы", null=True
            ),
        ),
    ]
