# Generated by Django 5.2 on 2025-05-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_question_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
