# Generated by Django 5.2 on 2025-05-05 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_alter_task_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("pdf", models.FileField(blank=True, null=True, upload_to="files/")),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.subject"
                    ),
                ),
            ],
        ),
    ]
