# Generated by Django 5.2 on 2025-05-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_alter_studymaterial_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer_image",
            field=models.ImageField(blank=True, null=True, upload_to="answer_images/"),
        ),
    ]
