# Generated by Django 5.2 on 2025-05-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0011_question_answer_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("text", "Текстовый ответ"),
                    ("number", "Числовой ответ"),
                    ("matrix", "Матрица"),
                    ("image", "Изображение"),
                ],
                max_length=10,
            ),
        ),
    ]
