# Generated by Django 5.2.1 on 2025-05-12 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0012_alter_question_question_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="task",
            name="completed",
        ),
    ]
