# Generated by Django 5.2.1 on 2025-05-12 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
        ("tasks", "0013_alter_task_options_alter_task_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompletedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_tasks",
                        to="index.profile",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completed_by_profiles",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "task")},
            },
        ),
    ]
